### ISSUE TITLE
Error when running application with version 0.3.4

### ISSUE THREAD

**Issue by jvanzella** [vlingo-net/vlingo-net-actors#46]
I was getting this error when installing the latest (0.3.4) version of Vlingo .net.  I thought I might be doing something wrong, so I downloaded the demo app (Ping/Pong) and ran it and it worked fine.  When I updated the NuGet to the latest (0.3.4) this error appeared when trying to run it, which is the same error I was getting when trying to run my code.

Stack trace:

`Dynamically generated class source for Vlingo.Actors.Examples.PingPong.Pinger__Proxy did not compile because: The type or namespace name 'Common' does not exist in the namespace 'Vlingo' (are you missing an assembly reference?)
   at Vlingo.Common.Compiler.DynaCompiler.Compile(Input input)
vlingo-net/actors: vlingo-net/actors: Generating proxy for test: IPinger
Dynamically generated class source for Vlingo.Actors.Examples.PingPong.Pinger__Proxy did not compile because: The type or namespace name 'Common' does not exist in the namespace 'Vlingo' (are you missing an assembly reference?)
   at Vlingo.Common.Compiler.DynaCompiler.Compile(Input input)
vlingo-net/actors: Actor instantiation failed because: Exception has been thrown by the target of an invocation.
vlingo-net/actors [Exception]: Exception has been thrown by the target of an invocation.
Actor instantiation failed because: Exception has been thrown by the target of an invocation.
   at Vlingo.Actors.Stage.CreateRawActor(Definition definition, Actor parent, IAddress maybeAddress, IMailbox maybeMailbox, ISupervisor maybeSupervisor, ILogger logger)
   at Vlingo.Actors.Stage.ActorProtocolFor[T](Definition definition, Actor parent, IAddress maybeAddress, IMailbox maybeMailbox, ISupervisor maybeSupervisor, ILogger logger)
vlingo-net/actors [StackTrace]:    at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean wrapExceptions, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor)
   at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean wrapExceptions, Boolean skipCheckThis, Boolean fillCache)
   at System.Activator.CreateInstance(Type type, Boolean nonPublic, Boolean wrapExceptions)
   at Vlingo.Actors.ActorFactory.ActorFor(Stage stage, Actor parent, Definition definition, IAddress address, IMailbox mailbox, ISupervisor supervisor, ILogger logger)
   at Vlingo.Actors.Stage.CreateRawActor(Definition definition, Actor parent, IAddress maybeAddress, IMailbox maybeMailbox, ISupervisor maybeSupervisor, ILogger logger)
vlingo-net/actors: vlingo-net/actors: FAILED: Actor instantiation failed because: Exception has been thrown by the target of an invocation.
vlingo-net/actors [Exception]: Actor instantiation failed because: Exception has been thrown by the target of an invocation.
vlingo-net/actors [StackTrace]:    at Vlingo.Actors.Stage.CreateRawActor(Definition definition, Actor parent, IAddress maybeAddress, IMailbox maybeMailbox, ISupervisor maybeSupervisor, ILogger logger)
   at Vlingo.Actors.Stage.ActorProtocolFor[T](Definition definition, Actor parent, IAddress maybeAddress, IMailbox maybeMailbox, ISupervisor maybeSupervisor, ILogger logger)`

**Comment by zpbappi** [comment]
@jvazella thanks for reporting the issue. We are looking into it.

**Comment by zpbappi** [comment]
@jvanzella We have pushed a new version of Vlingo.Actors and Vlingo.Common- which fixes the problem. We have also updated the PingPong example to use the updated v0.3.5 or Vlingo.Actors. Let us know if it fixes the problem in your project as well. Feel free to close the issue if this is resolved.

**Comment by jvanzella** [comment]
Fix is working.  Thank you for the quick turn around
